Masterminds/squirrel

part.go, select_test.go
Supports #37
It can be useful to use squirrel expressions as column names. In this case there is no need to create an SQL string by hand and think too much about escaping and other things.
With this proposal it will be easy to use `CASE` statements, for instance:
```
caseStmt := Case("number").
When(2, "two").
Else("big number")
qb := Select().Column(caseStmt).From("table")
```
=> Make squirrel.part support Sqlizer, not only string

expr.go, placeholder.go, placeholder_test.go
Benchmark result:
```
$ go test -bench .
PASS
BenchmarkPlaceholdersArray	30000000	        39.8 ns/op
BenchmarkPlaceholdersStrings	2000000000	         2.24 ns/op
ok  	squirrel	6.276s
```
=> Small optimization for placeholder generator.

insert.go, insert_test.go
Introduce SetMap function for InsertBuilder to set columns and values for an insert builder.
It's useful in case user want to insert or update with same dataset, depend on a special field. 
Something like:
```go
user := map[string]interface{}{"name": "Smith"}
if userID > 0 {
qb := sq.Update("user").SetMap(user).Where(Eq{"id": userID})
} else {
qb := sq.Insert("user").SetMap(user)
}
```
=> Propose InsertBuilder.SetMap() function.

case.go, case_test.go, expr.go, select_test.go, statement.go
Hi there! :)
Here's a proposal for support of `SELECT CASE` statements (http://dev.mysql.com/doc/refman/5.0/en/control-flow-functions.html#operator_case).
The commit contains test which shows an idea which is better to discuss before writing any real code. The interface is a matter of discussion.
Rationale of this proposal:
In current version of `squirrel` we have to pregenerate a subquery with `SELECT CASE`, like this, for example:
```
var values map[string]string = loadValues()
args = make([]interface{}, len(values)*2)
buf.WriteString("(SELECT CASE")
for k, v := range values {
buf.WriteString(" WHEN value = ? THEN ?")
args[i*2], args[i*2+1] = value, i
}
buf.WriteString(" END AS col1)")
qb := squirrel.Select(buf.String()).From("sometable")
```
But in this case nothing stops developer …
=> Support of CASE operator in SELECT query

select.go, select_test.go
I needed to join a nested select statement for a query I ran, so I did this change:
JoinClause now accepts an interface as first parameter and varadic arguments (like Where, etc.)
The sugar functions Join, LeftJoin, RightJoin still accept a string as first parameter (backwards compatibility ok), but also variadic arguments, so you can write e.g.
Select(`*`).From(`foo`).Join(`bar ON foo.baz = bar.baz AND bar.fubar > ?`, 42)
The JoinClause signature is also backwards compatible (string -> interface + variadic), but it now allows you to pass any Sqlizer (again, like Where), so you can e.g.
subselect := squirrel.Select(`*`).From(`foo`).Where(...)
select := squirrel.Select(`*`).From(`bar`).JoinClause(subselect.Prefix(`LEFT JOIN (`).Suffix(`) r ON bar.baz = r .baz`))
=> More flexible join clauses (string -> Sqlizer)

expr.go, expr_test.go
Previously, these just generated `""` which could cause invalid SQL.  Using portable true/false for the empty case fixes this.
=> Fix Empty And/Or SQL Generation

.travis.yml, select.go, select_test.go, squirrel.go, where.go
This PR addresses [issue #128](https://github.com/Masterminds/squirrel/issues/128).
The fix goes as follows: for `wherePart`, we check if the predicate implements `RawSqlizer` with its `ToSqlRaw()` method. `ToSqlRaw()` does just what `ToSql()` does, but skips `PlaceholderFormat.ReplacePlaceholders()`.
=> fix: nested select placeholders numbering

placeholder.go, placeholder_test.go, select_test.go
Adding a Placeholder Colon Format for Oracle DB users.
This looks and acts exactly like the Dollar Place Holder for Postgres. Except instead of using `$` it uses `:`
See: https://github.com/Masterminds/squirrel/issues/138
=> Adding Placeholder Colon format.

expr.go, placeholder.go
Removed `_` from a receiver names
Rewrote condition: removed else sections in `return` exists
=> Fixed some golint notices

squirrel.go, squirrel_ctx.go
found this useful in my projects, can be used to remove the explicitly checking for sql.DB and sql.TX
=> allow 3rd party wrappers to be used as runners.

squirrel.go
QueryContext and ExecContext were omitted from the interface, breaking some existing code.
Fixes #162
=> Fix Context methods with stdsqlRunner

stmtcacher.go, stmtcacher_ctx.go, stmtcacher_ctx_test.go, stmtcacher_noctx.go, stmtcacher_test.go
Due to some poor handling in my own codebase. I started creating lots of `*stmtCacher` instances.
While I was quickly discarding them I noticed that memory started to leak wherever something interacted with the shared `*sql.DB` connection pool. Upon revisiting the change made, I noticed we were creating all these proxy instances and started to wonder why even though these would get garbage collected memory kept growing. This lead me to realise that *sql.DB keeps its own pool of prepared statements: https://golang.org/src/database/sql/sql.go#L438
So I implemented this change just to validate that closing all those statements got rid of my memory issues and it did.
This change adds Close to:
- DBProxy
- DBProxyContext
- *stmtCacher
A call to *stmtCacher.Close will intentionally not close …
=> Add ability to Clear() statement cache

select.go, select_test.go
Hi.
`OFFSET` without `LIMIT` has no meaning in MySQL and cause of syntax error. And I see no ways to remove it. So I suggest to add `RemoveOffset` method.
=> SelectBuilder.RemoveOffset method added.

select.go
Pre-allocate memory to reduce the potential number of allocations and
reduce pressure on the gc.
=> Reduce memory allocations

placeholder.go, squirrel.go, squirrel_test.go
References: https://github.com/Masterminds/squirrel/issues/116
In DebugSqlizer lets check if the provided `Sqlizer` has a `GetPlaceholder` method. If so, retrieve the placeholder, otherwise default to the existing behavior of debugging against `?`
=> squirrel.DebugSqlizer: debug based on PlaceholderHolder (if present)

delete.go, expr.go, insert.go, select.go, update.go
This PR adds the `PrefixExpr(expr Sqlizer)` and `SuffixExpr(expr Sqlizer)` methods to all builders. 
This allows for more complex prefix expressions to be easily built in line, rather than having to create a seperate subquery builder, build the sql, and then use that as arguments to `.Prefix(sql, args...)`.
For example:
```go
sq.Select().
PrefixExpr(sq.ConcatExpr(
"WITH prefix AS (",
sq.Select("foo").From("bar"),
")"),
).
Columns("foo").
From("prefix")
```
=> Add `PrefixExpr` and `SuffixExpr` methods to all builders

squirrel.go, squirrel_ctx.go
This PR adds support for use of the `.RunWith` method of various statement builders with a wrapper of the standard `database/sql` interface, minus the *Context methods, whilst maintaining support for the full standard `database/sql`. 
Furthermore, this adds methods for wrapping these standard `database/sql` wrappers so that they can be used with the `QueryRowWith(QueryRower, ...)` methods.
=> Add support for standard `database/sql` runners sans Context methods

expr.go
Type was not exported, making it impossible to compile for instance
```golang
offset := func(i int) squirrel.expr {
return squirrel.Expr(fmt.Sprintf("select (now() at time zone 'utc') + interval '%d' nanosecond", i))
}
```
Note type `expr` was renamed to `Expression` as the `Expr` function is already public.
This does not break API compatibility.
=> Have Expr() return an exported type

placeholder.go, placeholder_test.go, select_test.go, squirrel_test.go
Added at placeholders (@p1) syntax. This usable with MS SQL Server.
Without this feature impossible to use squirrel with SQL Server.
=> MS SQL Server compatible placeholders

go.mod, select_test.go
The test `TestSelectBuilderToSql` fails because the expected string contains `"CROSS JOIN j6WHERE"` instead of `"CROSS JOIN j6 WHERE"`
##Solution
The expected string contains `"CROSS JOIN j6 WHERE"`
=> TestSelectBuilderToSql fixed

update.go, update_test.go
Sometimes it is necessary to use a subquery as the value of the set clause.
Code:
```go
Update.Table("a").Set("a", Select("a").From("b"))
```
Want:
```sql
UPDATE a SET a = (SELECT a FROM b)
```
Got:
```sql
UPDATE a SET a = SELECT a FROM b
```
This PR added parens for select statement.
=> Added paren for select statement in set clause

case.go, case_test.go, delete.go, delete_test.go, insert.go, insert_test.go, select.go, select_test.go, update.go, update_test.go
`MustSql()` method on `SelectBuilder` tends to be quite useful when working with less dynamic queries, however, at the moment, it's not possible to have the same flow with queries made with `CaseBuilder`, `DeleteBuilder`, `InsertBuilder` and `UpdateBuilder`. This PR adds `MustSql()` method to all of them.
Related PR: https://github.com/Masterminds/squirrel/pull/156
=> Add missing MustSql methods

part.go, select_test.go
Issue described at https://github.com/Masterminds/squirrel/issues/316
=> #316 JoinClause with subquery produces wrong dollar placeholders

select.go, select_test.go
I add remove columns method for select builder, it's useful for reuse others query conditions with others columns, e.g: use "COUNT(*)" feature before ( or after ) execute complex query conditions.
=> feat: add remove select builder columns method
