README.md
=> need `sq` in front of `sq.Dollar` in README.md

expr.go, expr_test.go
This commit adds support for doing less than, less than or equal to, greater than, and greater than or equal to. I added tests as well.
Please give feedback if not merged.
=> add support for >,>=,<,<=

select.go, select_test.go
Hi, All!
I've added Sqlized interface to the From clause. Now you can make a subquery in From statement. Please, review as soon as possible!
=> Added from clause as sqlized

update.go
This should close #57.
I took a stab at this, not sure if I got everything that is required for this. But I would really like to have this as part of squirrel. If I missed anything, let me know and I'll add it.
=> Add query api to update.

squirrel.go, squirrel_test.go
=> Add DebugSqlizer function

expr.go, expr_test.go
=> Fix handling of []byte in Eq.ToSql

delete.go, expr_test.go, insert.go, insert_test.go
InsertBuilder now supports below insert form
```sql
INSERT INTO table2 (field1) SELECT field1 FROM table1 WHERE field1 = ?
```
=> InsertBuilder now supports INSERT ... SELECT form

.travis.yml
Add go 1.10.x in `.travis.yml`
=> Travis: add go 1.10.x

expr.go, expr_test.go
=> Make empty Eq{} evaluate to true

expr.go, expr_test.go
I found that #143 was not only about nil value but also with slice and array. I refactored a bit the code for handling pointers and added some tests. If I missed same cases please leave a comment and I will fix
=> Handle pointers in expr

expr.go, expr_test.go
As my feature/issue #122 , I think it could be an useful feature for LIKE operations.
=> Add lk and nlk condition expressions.

select_test.go
=> Added test for issue#56

integration_test.go, squirrel.go
=> Fix stdsql context

delete.go, delete_test.go
=> Added query to delete builder

select.go, select_test.go
#60 Added limit all function to select builder
=> [#60] Added limit all method

select.go, select_test.go
=> Added mustsql functionality to select builder

expr.go, go.mod, go.sum
Add go-module support and fix lint issues
=> Add go-module support and fix lint issues

select.go, select_test.go
Just bumped into this issue https://github.com/Masterminds/squirrel/issues/139 and implemented OrderByClause.
=> Add OrderByClause to SelectBuilder

update.go, update_test.go
=> feat: update case support

delete_ctx.go, delete_ctx_test.go
Not sure why these were missing?
=> Add forgotten ctx methods for DeleteBuilder

expr.go, select_test.go
=> #301 Conjunction produces wrong dollar parameter placeholders

squirrel_ctx.go
Found a typo while reading the code.
=> Typo in comment

LICENSE
=> Change to get GitHub to recognize the license
